import { Product, VillageEvent } from '@/types'

// ── COTTAGES ──────────────────────────────────────────────────────────
export const COTTAGES: Product[] = [
  {
    id: 'c1',
    name: 'The Pokomo Suite',
    tag: 'Signature Cottage',
    category: 'cottage',
    description: 'Floor-to-ceiling farmland views. King bed suspended over open-plan living. The quintessential Ubuntu night.',
    longDescription: 'Perched at the highest point of the farm with unobstructed views across the Pokomo fields to the Rift escarpment. The suite features a suspended king bed, open-plan living with double-height ceilings, a private plunge bath, and a wraparound deck. Everything within reach was grown here.',
    price: 28500,
    unit: '/ night',
    capacity: 2,
    duration: 'Min. 2 nights',
    includes: ['Daily farm breakfast', 'Guided farm walk', 'Evening turndown', 'Welcome drink'],
  },
  {
    id: 'c2',
    name: "The Weaver's Nest",
    tag: 'Treetop Hideaway',
    category: 'cottage',
    description: 'Elevated among fig trees. Open-air studio built for writers, artists, and those who need to disappear beautifully.',
    price: 18000,
    unit: '/ night',
    sticker: 'Popular',
    capacity: 2,
    duration: 'Min. 1 night',
    includes: ['Farm breakfast', 'Writing desk & supplies', 'Private tree deck'],
  },
  {
    id: 'c3',
    name: "The Healer's Hut",
    tag: 'Wellness Retreat',
    category: 'cottage',
    description: 'Adjacent to Arohamai Spa. Wake to steam from the hot springs and transition into a full spa morning.',
    price: 22000,
    unit: '/ night',
    capacity: 2,
    includes: ['Farm breakfast', 'Thermal pool access', '1 spa treatment'],
  },
  {
    id: 'c4',
    name: 'The Farm Loft',
    tag: 'Working Farm Stay',
    category: 'cottage',
    description: 'Sleep above the chicken coops and herb garden. Morning collection basket included.',
    price: 14500,
    unit: '/ night',
    capacity: 2,
    includes: ['Morning egg collection', 'Herb garden access', 'Farm breakfast'],
  },
  {
    id: 'c5',
    name: 'The Baobab House',
    tag: 'Family Compound',
    category: 'cottage',
    description: 'Three-bedroom compound for families. Private kitchen, fire pit, and a resident tortoise named Gerald.',
    price: 55000,
    unit: '/ night',
    sticker: 'New',
    capacity: 8,
    includes: ['Private kitchen', 'Fire pit setup', 'Daily farm produce delivery', 'Guided walk × 2'],
  },
  {
    id: 'c6',
    name: 'The River Hut',
    tag: 'Solo Sanctuary',
    category: 'cottage',
    description: 'Single-occupancy hut on the riverbank. No phone signal by design. Journal, swim, exhale.',
    price: 11000,
    unit: '/ night',
    capacity: 1,
    includes: ['Farm breakfast', 'River swim access', 'Journal & pen'],
  },
]

// ── SPA ───────────────────────────────────────────────────────────────
export const SPA_TREATMENTS: Product[] = [
  {
    id: 'sp1',
    name: 'Ubuntu Ground Ritual',
    tag: 'Signature Treatment',
    category: 'spa',
    description: '90 mins. Red clay body wrap, cold river compress, and our Maasai oil massage. The full village in one session.',
    price: 8500,
    unit: '/ person',
    duration: '90 minutes',
    includes: ['Red clay body wrap', 'Cold river compress', 'Maasai oil massage', 'Herbal tea service'],
  },
  {
    id: 'sp2',
    name: 'Dawn Steam Ceremony',
    tag: 'Morning Ritual',
    category: 'spa',
    description: 'Sunrise steam hut with herbal infusions, cold plunge, and a breathwork guide. 75 mins.',
    price: 4200,
    unit: '/ person',
    duration: '75 minutes',
    includes: ['Herbal steam hut', 'Cold plunge pool', 'Breathwork guide'],
  },
  {
    id: 'sp3',
    name: 'Forest Couples Massage',
    tag: 'Couples',
    category: 'spa',
    description: 'Side-by-side deep tissue in our outdoor forest pavilion. Post-session herbal tea service.',
    price: 14000,
    unit: '/ couple',
    duration: '90 minutes',
    capacity: 2,
    includes: ['Outdoor forest pavilion', 'Deep tissue massage × 2', 'Herbal tea'],
  },
  {
    id: 'sp4',
    name: 'Farm-to-Face Facial',
    tag: 'Facial',
    category: 'spa',
    description: 'Fresh aloe vera, papaya enzyme, and turmeric from our garden. 60-min revitalisation.',
    price: 5500,
    unit: '/ person',
    duration: '60 minutes',
    includes: ['Garden-fresh botanicals', 'Enzyme exfoliation', 'Turmeric mask'],
  },
  {
    id: 'sp5',
    name: 'Baobab Body Polish',
    tag: 'Body Treatment',
    category: 'spa',
    description: 'Full-body exfoliation using ground baobab shell and shea. Leaves skin luminous. 45 mins.',
    price: 4800,
    unit: '/ person',
    duration: '45 minutes',
  },
  {
    id: 'sp6',
    name: 'Spa Half-Day',
    tag: 'Wellness Package',
    category: 'spa',
    description: 'Choose any two treatments plus thermal pool access, herbal lunch, and guided meditation.',
    price: 16500,
    unit: '/ person',
    sticker: 'Best Value',
    duration: 'Half day',
    includes: ['2 treatments of choice', 'Thermal pool all day', 'Farm-to-fork herbal lunch', 'Guided meditation'],
  },
]

// ── DINING ────────────────────────────────────────────────────────────
export const DINING: Product[] = [
  {
    id: 'd1',
    name: 'Farm Table Dinner',
    tag: 'Private Dining',
    category: 'dining',
    description: '8-course tasting menu for up to 12 guests. Open-air barn, live acoustic music, every dish traced to the field.',
    price: 18500,
    unit: '/ table',
    sticker: '48hrs notice',
    capacity: 12,
    includes: ['8-course tasting menu', 'Live acoustic music', 'Wine pairing available', 'Dedicated table host'],
  },
  {
    id: 'd2',
    name: "Forager's Sunrise Breakfast",
    tag: 'Experience Dining',
    category: 'dining',
    description: '5:30am farm walk with the head chef. Harvest your breakfast and cook it over the fire together.',
    price: 4800,
    unit: '/ person',
    duration: '3 hours',
    includes: ['Guided farm walk', 'Open-fire cooking', 'Full harvest breakfast'],
  },
  {
    id: 'd3',
    name: 'Nyama Choma Evening',
    tag: 'Village Feast',
    category: 'dining',
    description: 'Open-fire roast for up to 30 guests. Traditional spice rubs, fermented drinks, and drumming by the pit.',
    price: 65000,
    unit: '/ event',
    capacity: 30,
    includes: ['Open-fire roast', 'Traditional spice rubs', 'Fermented drinks', 'Live drumming'],
  },
  {
    id: 'd4',
    name: 'River Picnic Basket',
    tag: 'Curated Picnic',
    category: 'dining',
    description: 'Hand-packed basket delivered to your chosen river spot. Perfect for two or a small family.',
    price: 6500,
    unit: '/ basket',
    includes: ['Seasonal farm produce', 'Artisan breads', 'Cheese & charcuterie', 'Farm lemonade'],
  },
  {
    id: 'd5',
    name: 'Farm Kitchen Class',
    tag: 'Private Chef',
    category: 'dining',
    description: '3-hour cook-along with our farm chef. Seasonal ingredients, traditional Kenyan techniques.',
    price: 8500,
    unit: '/ person',
    duration: '3 hours',
    includes: ['Chef guidance', 'Recipe book', 'Full meal you cooked', 'Farm apron to keep'],
  },
  {
    id: 'd6',
    name: 'Acacia Sundowners',
    tag: 'Bush Bar',
    category: 'dining',
    description: 'Guided to an acacia grove at golden hour. Bush bar, charcuterie, and the Rift Valley to the west.',
    price: 5500,
    unit: '/ person',
    duration: '2 hours',
    includes: ['Guided walk to grove', 'Bush cocktails × 2', 'Charcuterie board', 'Rift Valley panorama'],
  },
]

// ── FARM WALKS ────────────────────────────────────────────────────────
export const FARM_WALKS: Product[] = [
  {
    id: 'fw1',
    name: 'Dawn Farm Safari',
    tag: 'Guided Walk',
    category: 'farm-walk',
    description: '2-hour guided walk through the wildlife corridor at sunrise. Track footprints, identify birds, learn from our Maasai guide.',
    price: 3500,
    unit: '/ person',
    duration: '2 hours',
    includes: ['Maasai guide', 'Binoculars', 'Track identification guide'],
  },
  {
    id: 'fw2',
    name: 'Medicinal Herb Trail',
    tag: 'Guided Walk',
    category: 'farm-walk',
    description: "90-min walk through the farm's medicinal herb gardens with our herbalist. Learn names, uses, and harvest rituals.",
    price: 2800,
    unit: '/ person',
    duration: '90 minutes',
  },
  {
    id: 'fw3',
    name: 'Nocturnal Farm Walk',
    tag: 'Night Walk',
    category: 'farm-walk',
    description: 'Guided night walk across the fields with spotlighting. Owls, civets, and the full Kenyan sky.',
    price: 3200,
    unit: '/ person',
    duration: '2 hours',
    includes: ['Spotlighting equipment', 'Stargazing guide', 'Hot chocolate on return'],
  },
  {
    id: 'fw4',
    name: 'Riverbank Nature Walk',
    tag: 'River Trail',
    category: 'farm-walk',
    description: "2-hour walk along the farm's river boundary. Birdwatching, fish identification, and riverside picnic stop.",
    price: 3000,
    unit: '/ person',
    duration: '2 hours',
    includes: ['Riverside picnic stop', 'Bird checklist', 'Binoculars'],
  },
  {
    id: 'fw5',
    name: 'Village Life Walk',
    tag: 'Cultural Walk',
    category: 'farm-walk',
    description: 'Walk through the surrounding community with a local guide. Meet farmers, artisans, and elders.',
    price: 3500,
    unit: '/ person',
    duration: '2.5 hours',
  },
]

// ── FARM ANIMALS ──────────────────────────────────────────────────────
export const FARM_ANIMALS: Product[] = [
  {
    id: 'fa1',
    name: 'Beekeeping Morning',
    tag: 'Animal Encounter',
    category: 'farm-animal',
    description: 'Suit up and visit 8 hives. Learn natural beekeeping, harvest comb honey, take a jar home.',
    price: 4200,
    unit: '/ person',
    duration: '2 hours',
    includes: ['Bee suit provided', 'Hive inspection', 'Raw honey harvest', 'Jar of honey to take home'],
  },
  {
    id: 'fa2',
    name: 'Camel Sunset Ride',
    tag: 'Adventure',
    category: 'farm-animal',
    description: '1-hour guided camel trek through acacia savanna to a sunset viewpoint. Sundowners included.',
    price: 8000,
    unit: '/ person',
    sticker: 'Favourite',
    duration: '1 hour',
    includes: ['Guided camel trek', 'Sunset viewpoint', 'Sundowners'],
  },
  {
    id: 'fa3',
    name: 'Goat & Dairy Morning',
    tag: 'Animal Encounter',
    category: 'farm-animal',
    description: 'Hand-milk our herd at 6am, make fresh paneer, and eat it for breakfast. The real farm life.',
    price: 2800,
    unit: '/ person',
    duration: '2 hours',
    includes: ['Herd milking session', 'Paneer-making class', 'Full breakfast'],
  },
  {
    id: 'fa4',
    name: 'Free Range Egg Harvest',
    tag: 'Morning Ritual',
    category: 'farm-animal',
    description: 'Morning collection of fresh eggs from our pasture-raised chickens. Learn about rotational grazing.',
    price: 1500,
    unit: '/ person',
    duration: '45 minutes',
  },
]

// ── FARM WORKSHOPS ────────────────────────────────────────────────────
export const FARM_WORKSHOPS: Product[] = [
  {
    id: 'fw6',
    name: 'Seed-to-Table Full Day',
    tag: 'Culinary Workshop',
    category: 'farm-workshop',
    description: 'Plant, harvest, and cook a full meal from our kitchen garden. The complete farm immersion.',
    price: 6500,
    unit: '/ person',
    duration: 'Full day',
    includes: ['Garden tools', 'Chef guidance', 'Full lunch', 'Recipe booklet'],
  },
  {
    id: 'fw7',
    name: 'Natural Dye & Weaving',
    tag: 'Craft Workshop',
    category: 'farm-workshop',
    description: 'Use farm-grown indigo and natural dyes. Weave a small piece to take home under local artisan guidance.',
    price: 5500,
    unit: '/ person',
    duration: '3 hours',
    includes: ['All materials', 'Artisan guide', 'Woven piece to keep'],
  },
  {
    id: 'fw8',
    name: 'Farm Fermentation Class',
    tag: 'Wellness Workshop',
    category: 'farm-workshop',
    description: 'Make kombucha, fermented vegetables, and raw vinegar from farm produce. 3 hours.',
    price: 4200,
    unit: '/ person',
    duration: '3 hours',
    includes: ['All ingredients', 'Jars to take home', 'Recipe guide'],
  },
  {
    id: 'fw9',
    name: "Kids' Mud Kitchen",
    tag: 'Children',
    category: 'farm-workshop',
    description: 'Supervised half-day for ages 4–12. Mud play, seed planting, animal feeding, and farm lunch.',
    price: 3500,
    unit: '/ child',
    duration: 'Half day',
    capacity: 10,
    includes: ['Supervised activities', 'Seed to plant & take home', 'Farm lunch'],
  },
]

// ── FARM HARVEST & FIELD ──────────────────────────────────────────────
export const FARM_HARVEST: Product[] = [
  {
    id: 'fh1',
    name: 'Harvest Morning',
    tag: 'Field Experience',
    category: 'farm-harvest',
    description: 'Join the farm team for the 6am harvest. Cut, pull, and carry produce from field to kitchen.',
    price: 2500,
    unit: '/ person',
    duration: '2 hours',
  },
  {
    id: 'fh2',
    name: 'Compost & Soil Session',
    tag: 'Field Experience',
    category: 'farm-harvest',
    description: 'Learn our closed-loop composting system and soil health practices. Half-day, hands in the earth.',
    price: 2200,
    unit: '/ person',
    duration: 'Half day',
  },
  {
    id: 'fh3',
    name: 'Irrigation Walk',
    tag: 'Field Experience',
    category: 'farm-harvest',
    description: "Follow the farm's water system from source to field. Gravity-fed and drip irrigation up close.",
    price: 1800,
    unit: '/ person',
    duration: '90 minutes',
  },
  {
    id: 'fh4',
    name: 'Farm Day Pass',
    tag: 'Day Pass',
    category: 'day-pass',
    description: 'Full farm access 8am–6pm. All trails, daily operations, spa thermal pools, and the restaurant.',
    price: 3500,
    unit: '/ person',
    includes: ['All farm trails', 'Thermal pool access', 'Restaurant access'],
  },
  {
    id: 'fh5',
    name: 'Spa + Farm Day',
    tag: 'Day Pass',
    category: 'day-pass',
    description: 'Day pass plus one 60-min treatment, farm-to-fork lunch, and thermal pool access all day.',
    price: 8500,
    unit: '/ person',
    sticker: 'Best Value',
    includes: ['Farm Day Pass', '60-min spa treatment', 'Farm-to-fork lunch', 'Thermal pool all day'],
  },
]

// ── EVENT PACKAGES ────────────────────────────────────────────────────
export const EVENT_PACKAGES: Product[] = [
  {
    id: 'ep1',
    name: 'The Village Gather',
    tag: 'Day Retreat',
    category: 'event-package',
    description: 'Intimate day retreat for up to 30 guests. Main event lawn, barn, farm access, and a curated meal.',
    price: 180000,
    unit: '/ event',
    capacity: 30,
    includes: [
      'Main event lawn & barn',
      'Soundsystem & lighting',
      'Farm access & guided walk',
      'Lunch or dinner at the farm table',
      'Dedicated event coordinator',
    ],
  },
  {
    id: 'ep2',
    name: 'The Full Ubuntu',
    tag: 'Village Buyout',
    category: 'event-package',
    description: 'Overnight full-village buyout for up to 80 guests. All 6 cottages, all facilities, all meals included.',
    price: 520000,
    unit: '/ event',
    sticker: 'Most Requested',
    featured: true,
    capacity: 80,
    includes: [
      'Exclusive use of all facilities',
      'All 6 cottages (16 beds)',
      'Farm-to-fork catering included',
      'Live music & fire ceremony',
      'Spa access for all guests',
      'Custom programme design',
      'Dedicated staff team of 12',
    ],
  },
  {
    id: 'ep3',
    name: 'The Board Retreat',
    tag: 'Corporate Leadership',
    category: 'event-package',
    description: 'Executive leadership retreat for 8–20 people. Facilitated programme, meeting barn, all meals on-site.',
    price: 280000,
    unit: '/ event',
    capacity: 20,
    includes: [
      'Dedicated meeting barn',
      'AV & presentation setup',
      'Breakout zones in nature',
      'All meals on-site',
      'Team-build activities included',
      'Optional: executive coach / facilitator',
    ],
  },
]

// ── PUBLIC EVENTS ─────────────────────────────────────────────────────
export const PUBLIC_EVENTS: Product[] = [
  {
    id: 'pe1',
    name: 'Seed-to-Table Workshop',
    tag: 'Public Workshop · 10 May',
    category: 'event-public',
    description: 'Open enrolment session. Hands-on farm cooking with a max of 12 guests.',
    price: 6500,
    unit: '/ person',
    capacity: 12,
  },
  {
    id: 'pe2',
    name: 'Full Moon Ceremony',
    tag: 'Cultural Night · 14 May',
    category: 'event-public',
    description: 'Traditional ceremony, fire, drumming, and communal feast under the full moon.',
    price: 4500,
    unit: '/ person',
  },
  {
    id: 'pe3',
    name: 'Maasai Beekeeping Day',
    tag: 'Public Workshop · 24 May',
    category: 'event-public',
    description: 'Led by our Maasai beekeeper. Harvest raw honey and learn hive management.',
    price: 4200,
    unit: '/ person',
    capacity: 8,
  },
  {
    id: 'pe4',
    name: 'Village Sound Bath',
    tag: 'Wellness Event · 31 May',
    category: 'event-public',
    description: 'Group sound healing in the open-air barn. Instruments sourced from across East Africa.',
    price: 3800,
    unit: '/ person',
  },
]

// ── CALENDAR EVENTS ───────────────────────────────────────────────────
export const CALENDAR_EVENTS: VillageEvent[] = [
  { id: 'cal1', name: 'Seed-to-Table Workshop', type: 'public', date: '2026-05-10', day: 10, month: 4, year: 2026, price: 6500, description: 'Open enrolment farm cooking workshop.', capacity: 12, spotsLeft: 4 },
  { id: 'cal2', name: 'Full Moon Ceremony', type: 'community', date: '2026-05-14', day: 14, month: 4, year: 2026, price: 4500, description: 'Traditional ceremony under the full moon.', capacity: 40, spotsLeft: 22 },
  { id: 'cal3', name: 'Private Corporate Retreat', type: 'corporate', date: '2026-05-17', day: 17, month: 4, year: 2026, price: 280000, description: 'Village fully reserved.', capacity: 20, spotsLeft: 0 },
  { id: 'cal4', name: 'Maasai Beekeeping Day', type: 'public', date: '2026-05-24', day: 24, month: 4, year: 2026, price: 4200, description: 'Led by our Maasai beekeeper.', capacity: 8, spotsLeft: 3 },
  { id: 'cal5', name: 'Farm Dinner Special', type: 'public', date: '2026-05-28', day: 28, month: 4, year: 2026, price: 18500, description: 'Special farm table collaboration dinner.', capacity: 12, spotsLeft: 6 },
  { id: 'cal6', name: 'Village Sound Bath', type: 'public', date: '2026-05-31', day: 31, month: 4, year: 2026, price: 3800, description: 'Group sound healing in the open-air barn.', capacity: 30, spotsLeft: 18 },
]
